M48
; DRILL file {KiCad 7.0.10} date Thursday, February 08, 2024 at 11:13:07 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-08T23:13:07+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0197
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0311
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0315
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T4C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T6C0.0433
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T7C0.0472
%
G90
G05
T1
X2.1Y-3.3
X2.9Y-3.3
X3.8Y-3.3
T2
X2.1376Y-1.8996
X2.1376Y-2.1004
X2.4624Y-1.8996
X2.4624Y-2.1004
T3
X2.2Y-2.4
X2.2Y-2.7
X2.2Y-3.0
X2.8Y-2.4
X2.8Y-2.7
X2.8Y-3.0
X3.3Y-2.7
X3.3Y-2.8969
X3.4Y-2.0
X3.5969Y-2.0
X3.7016Y-2.8
X3.8Y-2.2
X3.8Y-2.3969
X3.8Y-2.8
T4
X3.4Y-3.1
X3.6Y-3.1
T5
X3.0Y-2.6
X3.0Y-3.0
T6
X3.3Y-2.4
X3.4Y-2.4
X3.5Y-2.4
T7
X2.9Y-1.9
X2.9Y-2.0969
M30
